Brightspace/content-components

- components/d2l-content-uploader/src/components/main.js
- components/d2l-content-uploader/src/state/uploader.js
- components/d2l-content-uploader/src/util/s3-uploader.js
We use this to populate the topic title when it is first created.
> fix: d2l-content-uploader: reflect file name

- components/d2l-content-service-viewer/clients/content-service-client.js
- components/d2l-content-service-viewer/d2l-content-service-viewer.js
This is just a POC until the HM API is ready.
> fix: use LMS content service resource API

- capture/d2l-capture-producer/demo/index.html
- package.json
- Add script to start dev server for local capture producer
> Fix demo for capture producer

- capture/d2l-capture-producer/d2l-capture-producer.js
- capture/d2l-capture-producer/src/content-service-client.js
- Fix incorrect string names for finish success/error
- Add a missing API client function for creating a revision
- Automatically load and display new revision after successful finish
> US131578: Fix issues with Finishing in Producer

- applications/d2l-capture-central/src/pages/producer/d2l-capture-central-producer.js
- capture/d2l-capture-producer/README.md
- capture/d2l-capture-producer/d2l-capture-producer.js
The breadcrumbs broke after moving loading/saving logic into Producer.
> Fix breadcrumbs not working for current page in Capture Central Producer 

- capture/d2l-capture-producer/src/d2l-video-producer-captions.js
For lazy loading in the captions list (i.e. displaying more captions cues whenever the user scrolls down to the bottom), we attach an `IntersectionObserver` to a div at the bottom of the list.
However, during a session, this div can be destroyed and recreated. This can happen when copying a past revision, as it replaces the component's entire DOM with a "Loading" indicator. When this happens, the `IntersectionObserver`'s div reference becomes stale, and thus lazy loading stops working.
This PR fixes it by recreating the `IntersectionObserver` whenever the Captions Editor component finishes loading.
> Fix lazy load breaking in captions list when copying from revision

- core/d2l-content-uploader/src/components/main.js
- core/d2l-content-uploader/src/components/upload.js
- core/d2l-content-uploader/src/state/uploader.js
> fix: Remove unused code previously used for language selector during upload

- core/d2l-content-uploader/locales/en.js
- core/d2l-content-uploader/src/components/main.js
- core/d2l-content-uploader/src/components/preview.js
> fix: advanced editing dialog

- core/d2l-content-uploader/src/components/main.js
- core/d2l-content-uploader/src/components/preview.js
Related PR: https://github.com/Brightspace/lms/pull/16182
> Show d2l-content-viewer in upload preview if topic id is provided

- package.json
> Remove unused dependency on video-producer

- core/d2l-content-uploader/src/components/preview.js
Accidentally merged into master
here is the change:  
https://github.com/Brightspace/content-components/blob/c4be44bf1a9edac49ab893c5bc42d4ab8f3dbf00/core/d2l-content-uploader/src/components/preview.js#L113 to 
https://github.com/Brightspace/content-components/blob/c4be44bf1a9edac49ab893c5bc42d4ab8f3dbf00/core/d2l-content-uploader/src/components/preview.js#L127
> Make a dialog fullscreen

- core/d2l-content-uploader/src/components/preview.js
Accidentally merged into master
> Make a fullscreen dialog for producer

- capture/d2l-capture-producer/src/constants.js
Can't test on Windows locally, going to see how this works; will revert later if I find issues
> Test smaller size timeline

- core/d2l-content-uploader/src/components/preview.js
Merged few lines that were still work in progress
> Reverse dialog adjustments

- capture/d2l-capture-producer/d2l-capture-producer-editor.js
Fixes iOS captions rendering in producer
> Use autoplay to prerender video

- capture/d2l-capture-producer/d2l-capture-producer.js
> Forgot to bump with fix

- core/d2l-content-uploader/src/components/preview.js
> Always attempt to reload on error - don't check if URLs are expired

- core/d2l-content-viewer/d2l-content-viewer.js
Causes issues loading captions if the machine time is misconfigured
> Do not check for expiry on captions change

- capture/d2l-capture-producer/d2l-capture-producer.js
Fixes: [Producer X] No "Saved changes successfully" message the first time the draft is saved
> Refactor producer renderer

- core/d2l-content-viewer/d2l-content-viewer.js
Reverts Brightspace/content-components#162
> Revert "Removed on-track-changed listener"

- capture/d2l-capture-producer/d2l-capture-producer.js
Comment from Marks' PR https://github.com/Brightspace/content-components/pull/169: 
This fixes the issue where launching Producer on a processing revision shows only a loading spinner with no 'processing' message or any other controls.
It also fixes a minor bug where loading another revision would cause the top bar to briefly disappear.
The cause was that we were using a single 'loading' variable for two separate statuses:
The content object is not yet loaded (only happens at startup)
The selected revision is not yet loaded
By creating two separate 'loading' variables, we can allow the 'processing' message and the top bar to be shown after the content has loaded, but before the selected revision has finished processing and loading.
> Firefox - attempt to fix preview on reload

- capture/d2l-capture-producer/d2l-capture-producer-editor.js
This reverts commit 9370017efc54f6fc222c6170ae3ac4f085fa59fb and commit 5a2a6ad706b3a787a8713e2be91874c250e5a79a.
These fixes did not end up working on Cert.
> fix: Revert failed fixes for Firefox revision switching issue

- applications/d2l-capture-central/locales/en.js
- applications/d2l-capture-central/src/components/recycle-bin/recycle-bin-item.js
- applications/d2l-capture-central/src/components/videos/content-list-item.js
Add dialog to confirm that the user wants to delete a file.
> US135509 Add dialog when deleting capture-central content

- applications/d2l-capture-central/src/components/videos/content-list-item.js
- applications/d2l-capture-central/src/util/content-service-client.js
Fix for capture central download action opening videos in a new tab instead of downloading the file.
> capture central download fix

- applications/d2l-capture-central/src/components/videos/content-list-item.js
- applications/d2l-capture-central/src/d2l-capture-central-app.js
- applications/d2l-capture-central/src/pages/preview/d2l-capture-central-preview.js
- applications/d2l-capture-central/src/util/constants.js
- applications/d2l-capture-central/src/util/content-service-client.js
Add preview page for Capture Central. There is still some work to be done, e.g. add a "come back later" message when the current revision is processing, but adding this PR so the current work can be visible in staging.
> Add preview page for capture central

- applications/d2l-capture-central/src/components/videos/content-list-item.js
I missed this url when squashing a merge into my other commits (see #222)
> Fix preview url

- applications/d2l-capture-central/d2l-capture-central.js
- applications/d2l-capture-central/src/d2l-capture-central-app.js
- applications/d2l-capture-central/src/pages/encoder/d2l-capture-central-encoder.js
> Updating encoder launch endpoint to provide tenant id

- applications/d2l-capture-central/locales/en.js
- applications/d2l-capture-central/src/pages/folders/d2l-capture-central-folders.js
- applications/d2l-capture-central/src/pages/producer/d2l-capture-central-producer.js
See https://github.com/Brightspace/lms/pull/21067
> Rename Capture Central breadcrumbs to Media Library

- .eslintrc.json
- applications/d2l-capture-central/src/components/add-videos-dialog.js
- applications/d2l-capture-central/src/components/column-header.js
- applications/d2l-capture-central/src/components/content-filter-dropdown.js
- applications/d2l-capture-central/src/components/live-event-form.js
- applications/d2l-capture-central/src/components/recycle-bin/recycle-bin-list.js
- applications/d2l-capture-central/src/components/relative-date.js
- applications/d2l-capture-central/src/mixins/navigation-mixin.js
- applications/d2l-capture-central/src/pages/404/d2l-capture-central-404.js
- applications/d2l-capture-central/src/pages/folders/d2l-capture-central-folders.js
- applications/d2l-capture-central/src/pages/live-events/d2l-capture-central-live-events-create.js
- applications/d2l-capture-central/src/pages/live-events/d2l-capture-central-live-events-edit.js
- applications/d2l-capture-central/src/pages/live-events/d2l-capture-central-live-events-view.js
- applications/d2l-capture-central/src/pages/live-events/d2l-capture-central-live-events.js
- applications/d2l-capture-central/src/pages/reporting/d2l-capture-central-audit-logs.js
- applications/d2l-capture-central/src/pages/reporting/d2l-capture-central-live-events-reporting.js
- applications/d2l-capture-central/src/pages/reporting/d2l-capture-central-visits.js
- applications/d2l-capture-central/src/util/content-service-client.js
- applications/d2l-content-store/src/d2l-content-store-manage.js
- capture/d2l-capture-producer/src/d2l-capture-producer-timeline.js
- core/d2l-content-renderer/d2l-content-renderer.js
- core/d2l-content-topic-renderer/d2l-content-topic-renderer.js
- core/d2l-content-uploader/src/util/s3-uploader.js
Add an EsLint rule to add spaces between methods
> Add spaces between methods

- core/d2l-content-media-player/d2l-content-media-player.js
- core/d2l-content-media-player/lang/en.js
- core/d2l-content-media-player/src/clients/rest-client.js
- core/d2l-content-media-player/src/mixins/internal-localize-mixin.js
- core/d2l-content-renderer/d2l-content-renderer.js
- core/d2l-content-renderer/lang/en.js
Also add offscreen message about title and description of the media resource.
> Bug fixes and adding additional error messages.

- core/d2l-content-media-player/d2l-content-media-player.js
- core/d2l-content-media-player/lang/en.js
- core/d2l-content-renderer/d2l-content-renderer.js
- core/d2l-content-uploader/src/components/preview.js
Matches old component behaviour
> Show more informative langterm on preview page after uploading Video/Audio during processing

- core/d2l-content-media-player/d2l-content-media-player.js
- core/d2l-content-renderer/d2l-content-renderer.js
- core/d2l-content-renderer/lang/en.js
- core/d2l-content-scorm-player.js
- core/d2l-content-scorm-player/d2l-content-scorm-player.js
- core/mixins/revision-loader-mixin.js
Reverts Brightspace/content-components#321
> Revert "Revert "d2l content scorm player""
