- applications/d2l-capture-central/src/components/add-videos-dialog.js
- applications/d2l-capture-central/src/components/my-videos/content-list-item.js
- applications/d2l-content-store/src/components/content-list/content-list-item.js
This PR adds labels to selectable d2l-list-items that will be required in the near future in order to support changes that are being made to lists for selection, multi-selection, and multi-actions.
> Add required labels to selectable d2l-list-items.

- capture/d2l-capture-producer/d2l-capture-producer.js
- capture/d2l-capture-producer/src/constants.js
- capture/d2l-capture-producer/src/d2l-video-producer-chapters.js
- capture/d2l-capture-producer/src/timeline.js
The video editor is limited in functionality for large videos, since the precision of time selection was inversely related to the length of the video. Some simple math:
- The width of the timeline is `~1000` pixels
- For a video of length `x` seconds, each pixel would represent `x / 1000` seconds
- For a video that is `1000` seconds or less, each pixel would represent `<= 1` seconds. In this case, any second of the video could be reached by seeking, adding marks, or adding cuts
- **PROBLEM**: For a video longer than `1000` seconds, each pixel would represent `> 1` seconds. In this case, there would be a set of seconds that would be unreachable by seeking, adding marks, or adding cuts
To solve this problem, any point along the timeline can be zoomed. This can be done by dragging a slider …
> US130907 - Add zooming to timeline

- capture/d2l-capture-producer/d2l-capture-producer.js
- capture/d2l-capture-producer/locales/en.js
- capture/d2l-capture-producer/src/d2l-video-producer-captions.js
- capture/d2l-capture-producer/src/d2l-video-producer-chapters.js
Adds a tab selector to Producer, along with a new tab panel for Closed Captions. The Closed Captions tab has no contents or functionality yet.
> US131037: Create skeleton for Captions Editor

- applications/d2l-capture-central/src/pages/producer/d2l-capture-central-producer.js
- capture/d2l-capture-producer/src/d2l-video-producer-captions.js
Previously, Capture Central was still using the deprecated [video-producer in D2L Labs](https://github.com/BrightspaceUILabs/video-producer). This PR updates Capture Central's Producer page to use the new Producer component within this repo.
> US131039: Use new Producer component in Capture Central

- capture/d2l-capture-producer/d2l-capture-producer.js
When captions are uploaded, we add a `<track>` slot under the Media Player that points to a temporary URL for the captions data. If the `<track>` slot already exists, we simply update its `src` attribute.
However, as per the Web Component specifications, changing a slot's attributes won't fire the `slotchange` event. This causes captions upload to hang, as Media Player listens for `slotchange` before loading and parsing captions.
To ensure that `slotchange` is always fired on upload, this PR removes and re-adds the `<track>` slot during the upload process.
> US131578: Fix captions upload hanging after loading existing captions

- core/d2l-content-viewer/d2l-content-viewer.js
- core/d2l-content-viewer/src/clients/rest-client.js
I didn't realize that this repo was doing auto-versioning, so in my previous PR, my change to v3 in package.json didn't get applied. I could either revert that PR or make it backwards compatible, and making it backwards compatible is easy, so I went with that option. This PR just adds back support for the old d2l-content-viewer params `href` and `captions-href`. We can remove support later when we bump to v3.
> fix: Make backwards compatible with v2

- capture/d2l-capture-producer/d2l-capture-producer-editor.js
When the user seeks to a new time position in the audio/video file, the timeline is automatically updated to match.
However, this was causing a null reference error for audio files, because the timeline is not initialized for formats that don't yet support cuts and chapters.
> fix: Prevent null error when seeking while timeline is disabled

- capture/d2l-capture-producer/src/d2l-video-producer-captions.js
Previously, we displayed captions cues' start and end timestamps in an input text control. This was misleading, as editing the input text did not actually modify the cue's timestamp data.
In the future, we may come back and allow the user to manually edit the timestamps using an input text. However, this functionality is not necessary for release, as it was not implemented in legacy Producer nor the Audio/Video Note Captions Editor.
Trello card for implementing manual timestamp editing: https://trello.com/c/ed9Zotwe
> fix: Display captions cues timestamps as non-editable text

- capture/d2l-capture-producer/d2l-capture-producer-editor.js
- capture/d2l-capture-producer/d2l-capture-producer.js
- capture/d2l-capture-producer/demo/demo-video-producer.js
- capture/d2l-capture-producer/src/d2l-video-producer-captions.js
- Fixed a bug where Producer's loading overlay was wider than Producer itself, causing the loading spinner to appear on the right edge of the page instead of the center.
- Fixed a bug where the timeline would appear before Producer finished loading.
- In the captions cue list item layout, the "Start" and "End" labels are now horizontally aligned with the edge of the text input box.
- To prevent confusing the user with two progress bars (Producer's timeline and Media Player's seek bar), Producer passes a `hide-seek-bar` attribute to the Media Player. This attribute will be implemented in a followup PR in the Media Player repo: https://github.com/BrightspaceUILabs/media-player/pull/114
> fix: Cosmetic fixes in Producer X

- capture/d2l-capture-producer/d2l-capture-producer.js
- capture/d2l-capture-producer/src/content-service-client.js
- API requests for captions and metadata now use the respective `/resource` routes in Content Service.
- Captions and metadata are only saved if they have been modified. If only captions were modified, then only captions are saved (same for metadata).
- If a locale has captions, but the user clears all cues and saves, the captions for that locale is deleted. (Before, we saved an empty captions file.)
- Producer will now check if the current revision's `captions` array has an entry for the current locale, before requesting captions from Content Service. If the locale can't be found in the `captions` array, no API request is made and Producer displays empty captions.
> feat: Use the Content Service's Resource Model in Producer X

- core/d2l-content-uploader/src/components/upload.js
Remove HTML element which displays the language selector, along with corresponding Javascript classes.
> fix: Remove language selector from upload dialog

- capture/d2l-capture-producer/d2l-capture-producer.js
- capture/d2l-capture-producer/locales/en.js
- capture/d2l-capture-producer/src/content-service-client.js
- Load and display the original revision's media file.
- When a new draft revision is created, the `formats` and `sourceFormat` of the current revision are carried over. This prevents issues such as Video Notes (which should always be low-definition) gaining a high-definition format on save.
> fix: Fixes for loading and saving media files in Producer X

- capture/d2l-capture-producer/d2l-capture-producer.js
- capture/d2l-capture-producer/src/content-service-client.js
I'm using this in local dev, because for some reason the response `statusText` value is an empty string.
That would break my local producer, causing an error message **An error occurred while loading chapters and timeline cuts**, preventing the timeline from loading, and breaking the save draft and finish buttons
> Work around for missing statusText in response

- capture/d2l-capture-producer/d2l-capture-producer.js
When the user loads a past revision and hasn't made any edits yet, it might be confusing to see that they can Finish. Now, the user must save a draft or make edits in order to Finish a past revision.
> fix: Disable "Finish" button if past revision is loaded with no changes

- capture/d2l-capture-producer/d2l-capture-producer.js
Before: if the user loads a non-draft revision and starts Auto-Generation, Producer would incorrectly load and display the old revision instead of the new revision.
> fix: Load new revision after starting Auto-Generation on non-draft

- capture/d2l-capture-producer/d2l-capture-producer.js
Once processing is complete, we need to reload the revisions list because auto-generation adds new captions entries to the processed revision.
> fix: Prevent captions showing up empty after auto-generation finishes

- capture/d2l-capture-producer/d2l-capture-producer-editor.js
This is to ensure that the user still has a way to seek through the file when cuts and chapters are disabled. (e.g. for Audio files)
> fix: Display Media Player's seekbar when Producer's timeline is disabled

- capture/d2l-capture-producer/d2l-capture-producer.js
When a revision has adjusted captions, and those captions haven't been edited yet, Producer should load and display the adjusted captions. (But Producer will always save to unadjusted.)
> fix: Fall back to adjusted captions when unadjusted doesn't exist (US133334)

- capture/d2l-capture-producer/d2l-capture-producer.js
- capture/d2l-capture-producer/src/content-service-client.js
- Falling back to adjusted captions is now handled on the Content Service backend. So this PR reverts #103.
- The DELETE captions route no longer takes an "adjusted" parameter, so Producer's calls to that route have been modified accordingly.
The Content Service changes can be found in https://github.com/Brightspace/d2l-content-service/pull/1745.
> US133334: Update Producer to handle changes to unadjusted captions API

- capture/d2l-capture-producer/d2l-capture-producer-editor.js
- capture/d2l-capture-producer/d2l-capture-producer.js
- core/d2l-content-uploader/src/components/preview.js
- core/d2l-content-viewer/d2l-content-viewer.js
- package.json
I'll update the PR with the new media-player version once https://github.com/BrightspaceUILabs/media-player/pull/118 is merged. I'm going to bump the major version there.
> Recover from URL expiry; add support for new media-player mediaType attribute

- capture/d2l-capture-producer/d2l-capture-producer-editor.js
- capture/d2l-capture-producer/demo/demo-video-producer.js
- Fixes an issue where the grey "highlight" colour on the timeline buttons would disappear after clicking somewhere else on the page.
- The timeline mode buttons are now radio buttons. This allows the highlight colour to automatically toggle on for the button that was last clicked, and toggle off for the other two buttons.
- Added a missing `mediaType` attribute to the Media Player in the Producer X demo. Without it, the Media Player would not finish loading.
https://user-images.githubusercontent.com/9592685/144130689-da7276d8-4541-4a15-96cf-c2fd89f4bec8.mp4
> fix: Maintain timeline mode selection highlight + fix Producer demo

- capture/d2l-capture-producer/src/d2l-video-producer-captions.js
The window scroll was causing the "Advanced Editing" dialog to become cut-off in Safari. More details: https://trello.com/c/6aahlajV
Solution from: https://stackoverflow.com/a/67433987. Verified this fix in Safari, Firefox, Chrome, Edge.
Safari recording:
https://user-images.githubusercontent.com/9592685/144883909-b1a84e72-368f-48cb-b6b8-dc50decbdbb6.mp4
> fix: Prevent window from scrolling during captions auto-scroll

- capture/d2l-capture-producer/d2l-capture-producer-editor.js
- core/d2l-content-uploader/src/components/preview.js
Max dialog size is set to 1200px
If the window was resized - reset dialog location
min-width: 170px is required to fix broken button styles in Firefox
> Fix dialog size

- capture/d2l-capture-producer/d2l-capture-producer.js
The previous code allowed the "Save Draft" button to be enabled, even when there are not user edits, if:
- The currently-selected revision is the latest revision; and
- The latest revision is a non-draft
To prevent confusion, we remove this case.  
This simplifies the "Save Draft" button's behaviour to only become enabled if:
- There are changes; and/or
- The currently-loaded revision is not the latest
> fix: Disable "Save Draft" button when there are no edits yet

- capture/d2l-capture-producer/d2l-capture-producer-editor.js
Previously, Producer's Media Player would jump to the start time of a cue whenever that cue's start or end time was edited.
However, this jumping caused some functional glitches. Additionally, we decided that this behaviour would be confusing for most users.
Before:
https://user-images.githubusercontent.com/9592685/145086637-255de74c-8075-4432-95fc-4650ae424c05.mp4
After:
https://user-images.githubusercontent.com/9592685/145086663-1860dae1-3190-43fb-b9cd-b5709b3464ff.mp4
> fix: Do not make Media Player jump to cue start when cue time is edited

- capture/d2l-capture-producer/d2l-capture-producer-editor.js
The current timeline mode is tracked by a variable, so the checked state of the timeline mode buttons should be synced to that variable.
On initial load, that variable is set to Seek mode. This fix ensures that the Seek button is highlighted on initial load.
> fix: Preselect the Seek button to match Producer's initial timeline mode

- core/d2l-content-viewer/d2l-content-viewer.js
fix for https://trello.com/c/zHhjjNxh/259-media-player-if-a-video-has-multiple-captions-in-english-eg-us-uk-canada-only-one-can-be-displayed
> Do not slice srclang

- capture/d2l-capture-producer/d2l-capture-producer-editor.js
When a cue's "Sync start time" button is clicked, and the Media Player's current time position is **later** than the cue's end time, the cue's end time is automatically updated using this formula:
```
newEndTime = newStartTime + (oldEndTime - oldStartTime)
```
to ensure that the cue's duration stays the same.
However, this can cause the new end time to go past the audio/video file's duration.
The fix is to set end time to the file duration, if the calculated end time would have gone past it.
> fix: Prevent cue end time from going past file duration when syncing cue start time

- core/d2l-content-uploader/src/components/upload.js
- core/d2l-content-uploader/src/util/content-service-client.js
I found that you can use extensions instead of mime types, so I think that's a better option since mime types are inconsistent between browsers. I tested in Chrome, Safari, and Firefox in local dev.
> Use extensions instead of CS supported mime types to determine which video/audio files can be uploaded

- core/d2l-content-viewer/src/clients/rest-client.js
I'm not really sure if this is causing issues, but it could explain some weird stuff I've seen. Either way, it seems very wrong to cache the response for getting the signed URL
> Don't use cache for call to get media url

- capture/d2l-capture-producer/src/content-service-client.js
Caching with GetOriginalSignedUrlForRevision was causing an issue with URL expiry, but I figure I should just make it so that all GET requests in Producer don't cache by default. If there's a GET call in the future we should cache for, we can add a new parameter to _fetch to support that.
> Producer - Never cache on GET requests

- capture/d2l-capture-producer/d2l-capture-producer.js
Want to keep the changes minimal. This is to support https://trello.com/c/G6xrWO0F/273-producer-x-you-can-close-the-producer-and-lose-your-changes-without-getting-any-warning (Peter's request)
When there are no changes, the user can close the tab or leave the page __without__ a prompt.
When there are changes this browser native dialog will appear:
Clicking "Cancel" will do nothing, and the user can manually save. Clicking "Leave" will force the page to unload and unsaved changes are lost.
Peter wanted the dialog to auto save, but that would have been more complicated and possibly introduce bugs.
> Producer: ask before exit if there are unsaved changes

- capture/d2l-capture-producer/d2l-capture-producer-editor.js
- capture/d2l-capture-producer/d2l-capture-producer.js
Attempt to fix Firefox issue with broken preview: https://trello.com/c/TnBQ51mi/324-producer-x-video-preview-stops-working-after-creating-a-draft-revision-and-then-swapping-between-revisions
> Use source node instead of src attribute

- capture/d2l-capture-producer/src/constants.js
- capture/d2l-capture-producer/src/d2l-video-producer-captions.js
If a cue's text is too long, Saving and Finishing will fail.
Captions auto-generation should produce, at most, 80 characters per cue. As such, 100 characters should be a safe upper limit.
I've verified locally that Save and Finish work when there are several cues with 100 characters.
> fix: Limit the text of individual captions cues to 100 characters

- capture/d2l-capture-producer/d2l-capture-producer-editor.js
Couldn't verify that this fixes the issue on local.
However, I verified that setting `currentTime = 0` always forces the Media Player to do a seek operation, even if the Media Player is already at 00:00:00. So the seeking should work.
> fix: Attempt to fix Firefox revisions bug by seeking to start on load

- .github/workflows/release.yml
- README.md
- capture/d2l-capture-producer/README.md
[BrightspaceUI/actions recently renamed its 'master' branch to 'main'](https://github.com/BrightspaceUI/actions).
Our release workflow still pointed to master, which was causing release builds to fail.
> fix: Change semantic-release branch from 'master' to 'main'

- .github/workflows/release.yml
- README.md
- capture/d2l-capture-producer/README.md
[The default branch for semantic-release is "main"](https://github.com/BrightspaceUI/actions/tree/main/semantic-release), so this caused release builds to fail.
This is a quick fix for the upcoming release. In the long term, we should rename "master" to "main".
> fix: Set semantic-release's default branch to "master" for now

- capture/d2l-capture-producer/d2l-capture-producer-editor.js
In order for the tooltips' positions to anchor correctly, one of their ancestor elements needed to have an explicitly-defined "position" attribute.
> fix: Prevent tooltips from going off-position when window is small

- capture/d2l-capture-producer/d2l-capture-producer-editor.js
- capture/d2l-capture-producer/d2l-capture-producer.js
- capture/d2l-capture-producer/src/constants.js
fixes https://trello.com/c/oisRsKYy and an issue where a success toast notification for saving/finishing would be red (and use the error text when finishing) if saving/finishing had previously resulted in an error
> adjust hitbox height with zoom and reset producer error state

- capture/d2l-capture-producer/src/timeline.js
https://trello.com/c/0e3Pez5r/245-content-video-make-cuts-in-and-out-timestamps-nullable-in-the-lms-model-class
Also see  [#17238](https://github.com/Brightspace/lms/pull/17238)
> Make out parameter in cuts nullable

- applications/d2l-capture-central/src/components/my-videos/content-list-item.js
- applications/d2l-capture-central/src/components/my-videos/content-list.js
Hide checkboxes from 'My Videos' item list in Capture Central until bulk actions are supported.
> US134919 Hide checkboxes from 'My Videos' item list

- applications/d2l-capture-central/src/components/capture-central-list.js
- applications/d2l-capture-central/src/components/my-videos/content-list.js
- applications/d2l-capture-central/src/mixins/content-search-mixin.js
- applications/d2l-capture-central/src/util/content-service-client.js
Move some methods out of ContentList and into a new class so that RecycleBin and ContentList can share those methods (will add RecycleBin in a separate PR)
> Move methods for reusability

- applications/d2l-capture-central/src/state/routing-store.js
[The 'Edit Live Event' page observes the query parameters in the routing store. When they change, it then checks if the subView (the last part of the URL) is set to 'edit' before reloading the page content.](https://github.com/Brightspace/content-components/blob/a714fcdbef9f6b675d95889db68124d7ecbde4ed/applications/d2l-capture-central/src/pages/live-events/d2l-capture-central-live-events-edit.js#L122)
The issue was that the query parameters in the routing store were being updated BEFORE the subView, causing the page to reload at the wrong time with incorrect query parameters.
The solution is simply to update the routing store's subView value before updating the query parameters, to ensure the page always reloads as expected.
> Fix 'Edit Live Event' page breaking after first time it is viewed

- applications/d2l-capture-central/src/d2l-capture-central-app.js
Live Events are no longer on the roadmap as they require more planning.  
This PR removes the link to the "Live Events" page, and removes the URL routings to all Live Events pages. Attempting to go to those pages will redirect to a 404 page.
The code for Live Events will remain in the repo, in case we decide to re-add it down the line.
> US134918: Hide and prevent access to "Live Events" pages

- applications/d2l-capture-central/src/d2l-capture-central-app.js
- applications/d2l-capture-central/src/pages/d2l-capture-central-landing.js
- applications/d2l-capture-central/src/state/permission-store.js
Originally, the landing page checked the value of the "Can Manage Capture Central" variable. If false, it would redirect to 404 to prevent user access. The previous code used an incorrect variable reference, hence the landing page always redirected to 404.
The proper permission to use in this case would be "Can _Access_ Capture Central", rather than "Can _Manage_ Capture Central". To fix that, this commit adds a getter for "Can Access Capture Central"" in `PermissionStore` and updates the landing page to use it.
> fix: Stop landing page from always redirecting to 404

- core/d2l-content-uploader/locales/en.js
- core/d2l-content-uploader/src/components/preview.js
- core/d2l-content-uploader/src/util/content-service-client.js
Because of the recent cost-cutting changes to transcoding, a video file might not have an SD transcode available.
After uploading, d2l-content-uploader's Preview page tries to load both SD and HD formats. If SD doesn't exist, the 404 causes the dialog to break.
To fix this, we now check for 404 when fetching each media format. If a 404 is received, then that format isn't passed to the Media Player.
In the exceptional case where all formats return 404, meaning no transcodes were produced, we display a "This media file failed to be processed" error.
> fix: Fix d2l-content-uploader not displaying preview when SD is missing

- applications/d2l-capture-central/locales/en.js
- applications/d2l-capture-central/src/components/capture-central-list.js
- applications/d2l-capture-central/src/components/content-file-drop.js
- applications/d2l-capture-central/src/components/recycle-bin/recycle-bin-list.js
- applications/d2l-capture-central/src/components/videos/content-list.js
- applications/d2l-capture-central/src/pages/videos/d2l-capture-central-videos.js
- applications/d2l-capture-central/src/util/constants.js
- applications/d2l-capture-central/src/util/media-type-util.js
- added 5GB limit to match max file size for s3 upload (not multipart)
- restricted upload to allow only the supported video types
- removed drag and drop upload from recycle bin
> capture central upload size and file type restrictions

- applications/d2l-capture-central/locales/en.js
- applications/d2l-capture-central/src/components/videos/content-list-item.js
The "Preview" page can now be accessed in two ways:
- Clicking anywhere on a video list item
- Opening a video list item's menu and selecting "Preview" (this replaces the "Preview" icon button that we previously had)
> feat: Access preview by clicking on video row or "Preview" option (US136519)

- applications/d2l-capture-central/src/mixins/content-search-mixin.js
- applications/d2l-capture-central/src/state/uploader.js
- applications/d2l-capture-central/src/util/content-service-client.js
- videos uploaded from Capture Central now have `clientApp=LmsCapture`
- search now filters out videos with the following clientApp: `LOR`, `Portfolio`, and `VideoNote`
> use clientApp in capture central upload/search

- applications/d2l-capture-central/src/components/videos/content-list-item.js
Setting href makes the page go to `<instance url>/d2l/preview/<content id>` instead of `<instance url>/d2l/wcs/capture-central/<org unit id>/preview/<content id>`
> Use previewUrl to go to preview from row

- applications/d2l-capture-central/src/components/videos/content-list-item.js
- applications/d2l-capture-central/src/components/videos/content-list.js
Fixes the issue where renaming a video after transferring ownership reverts the ownership change (https://trello.com/c/63MlfG0D). Also fixes a similar issue where transferring ownership after renaming reverts the name change.
> update content after rename or transfer succeeds

- capture/d2l-capture-producer/src/d2l-video-producer-captions.js
I was reviewing the last update in staging and noticed there was one error that somehow got missed. I honestly think I might have clicked control Z or something because I remember going over this on call with Mark. 
It looks like I copy and pasted a line of code in start time focus out to end time focus out and forgot to change a variable name.
> feat: Bump version for editing timestamp text inputs in Producer

- applications/d2l-capture-central/src/components/videos/content-list-header.js
- applications/d2l-capture-central/src/components/videos/content-list-item.js
- applications/d2l-capture-central/src/d2l-capture-central-app.js
Headers are broken so it doesn't look the best but it's functional for now. Maybe we can improve the appearance in the future.
https://trello.com/c/B9Hekar2/240-capture-central-android-video-menu-is-cropped-on-android-device
> Uncrop capture view on mobile

- applications/d2l-capture-central/src/d2l-capture-central-app.js
Seems like the old method of accessing the `d2l-capture-central-preview` node was not reliable so the preview's `firstUpdated` method never got called.
> Fix preview not loading

- applications/d2l-capture-central/src/d2l-capture-central-app.js
- applications/d2l-capture-central/src/pages/preview/d2l-capture-central-preview.js
This is what the preview looks like with shorter height:
> Make preview dialog height shorter

- web-test-runner.config.js
d2l-content-store tests, specifically content-list.test.js and content-list-item.test.js were causing other tests to fail with `Error: Uncaught Error: LabelledMixin: "d2l-list-item" is missing a required "label" attribute (node_modules/@brightspace-ui/core/mixins/labelled-mixin.js:208)` because the error is thrown after a delay of 3 seconds. Since we don't use d2l-content-store, excluding these tests to prevent them from causing failures in other tests.
Other places where we use `d2l-list-item` have the `label` attribute or do not require it.
> exclude d2l-content-store from tests

- applications/d2l-capture-central/src/components/capture-central-list.js
- applications/d2l-capture-central/src/components/recycle-bin/recycle-bin-item.js
- applications/d2l-capture-central/src/components/recycle-bin/recycle-bin-list.js
- applications/d2l-capture-central/src/components/videos/content-list-item.js
- applications/d2l-capture-central/src/components/videos/content-list.js
- applications/d2l-capture-central/src/mixins/content-search-mixin.js
- applications/d2l-capture-central/src/state/uploader.js
- Combines 2 object destructuring statements into 1.
- Renames all instances of `thumbnail` to `poster`, in order to differentiate the terminology from timeline thumbnails. This also better aligns with the name of the poster resource in Content Service.
> fix: Refactor video poster code in Capture Central for clarity

- core/d2l-content-media-player/d2l-content-media-player.js
- core/d2l-content-media-player/lang/en.js
Incorporating recent changes made to d2l-content-viewer to support revisions with no formats (load source video).
> Incorporating changes to load source video if no formats specified

- core/d2l-content-viewer/d2l-content-viewer.js
Lessons are missing some of the content-viewer translations. To not rely on it - we should fallback to English
> Have a fallback for the source label

- applications/d2l-capture-central/src/components/videos/content-list-item.js
It causes null reference exception in the browser on click
> Fixed processing video on click issue

- core/d2l-content-activity-renderer/d2l-content-activity-renderer.js
Also, set width of d2l-content-renderer component to 100%.
Depends on https://github.com/Brightspace/lms/pull/22989
> Update d2l-content-activity-viewer to work without requiring topicId to be passed in

- capture/d2l-capture-producer/src/captions-utils.js
- capture/d2l-capture-producer/test/captions-utils.test.js
This fix prevents br tags from being added to the cues in Producer when an srt file is uploaded.
Related to: https://github.com/BrightspaceUILabs/media-player/pull/173
> DE48462 - replace all br tags

- core/mixins/revision-loader-mixin.js
A bug in some refactoring I did yesterday
> Fix mixin - pass in contextType/Id if available
